# Start the testnet server with the command 'docker-compose up -d'

ipfs:
  image: ipfs/go-ipfs


koa:
  build: ./production/
  dockerfile: Dockerfile
  ports:
    - "3210:3210"  # <host port>:<container port>
#  volumes:
#    - ./logs:/home/coinjoin/consolidating-coinjoin/logs
#    - ./keys:/home/safeuser/keys
  links:
    - ipfs
  restart: always
