# Start the testnet server with the command 'docker-compose up -d'

koa:
  build: ./production/
  dockerfile: Dockerfile
  links:
    - koa-mongodb
  ports:
    - "3210:3210"  # <host port>:<container port>
  volumes:
#    - ./logs:/home/coinjoin/consolidating-coinjoin/logs
#    - ./keys:/home/safeuser/keys

  restart: always
