# Start the testnet server with the command 'docker-compose up -d'

webserver:
  build: ./production/
  dockerfile: Dockerfile
  container_name: webserver
  ports:
    - "3210:3210"  # <host port>:<container port>
    - "4231:4002"  # IPFS
  volumes:
    - ./ipfs-data:/home/safeuser/ipfs-web-server/ipfs-data
  restart: always
